<style> @media print{ .hljs{overflow: visible; word-wrap: break-word !important;} }</style></head><body><div class="markdown-body">
<h1 id="toc_0">异常</h1>

<h2 id="toc_1">目标</h2>

<ul>
<li>异常的概念</li>
<li>捕获异常</li>
<li>异常的传递</li>
<li>抛出异常</li>
</ul>

<h2 id="toc_2">01. 异常的概念</h2>

<ul>
<li>程序在运行时，如果 <code>Python 解释器</code> <strong>遇到</strong> 到一个错误，<strong>会停止程序的执行，并且提示一些错误信息</strong>，这就是 <strong>异常</strong></li>
<li><strong>程序停止执行并且提示错误信息</strong> 这个动作，我们通常称之为：<strong>抛出(raise)异常</strong></li>
</ul>

<p><img src="media/14989636063700/001_%E5%BC%82%E5%B8%B8%E7%A4%BA%E6%84%8F%E5%9B%BE.png" alt="001_异常示意图" style="width:480px;"/>￼</p>

<blockquote>
<p>程序开发时，很难将 <strong>所有的特殊情况</strong> 都处理的面面俱到，通过 <strong>异常捕获</strong> 可以针对突发事件做集中的处理，从而保证程序的 <strong>稳定性和健壮性</strong></p>
</blockquote>

<h2 id="toc_3">02. 捕获异常</h2>

<h3 id="toc_4">2.1 简单的捕获异常语法</h3>

<ul>
<li>在程序开发中，如果 <strong>对某些代码的执行不能确定是否正确</strong>，可以增加 <code>try(尝试)</code> 来 <strong>捕获异常</strong></li>
<li>捕获异常最简单的语法格式：</li>
</ul>

<pre><code class="language-python">try:
    尝试执行的代码
except:
    出现错误的处理
</code></pre>

<ul>
<li><code>try</code> <strong>尝试</strong>，下方编写要尝试代码，不确定是否能够正常执行的代码</li>
<li><code>except</code> <strong>如果不是</strong>，下方编写尝试失败的代码</li>
</ul>

<h4 id="toc_5">简单异常捕获演练 —— 要求用户输入整数</h4>

<pre><code class="language-python">try:
    # 提示用户输入一个数字
    num = int(input(&quot;请输入数字：&quot;))
except:
    print(&quot;请输入正确的数字&quot;)
</code></pre>

<h3 id="toc_6">2.2 错误类型捕获</h3>

<ul>
<li><p>在程序执行时，可能会遇到 <strong>不同类型的异常</strong>，并且需要 <strong>针对不同类型的异常，做出不同的响应</strong>，这个时候，就需要捕获错误类型了</p></li>
<li><p>语法如下：</p></li>
</ul>

<pre><code class="language-python">try:
    # 尝试执行的代码
    pass
except 错误类型1:
    # 针对错误类型1，对应的代码处理
    pass
except (错误类型2, 错误类型3):
    # 针对错误类型2 和 3，对应的代码处理
    pass
except Exception as result:
    print(&quot;未知错误 %s&quot; % result)
</code></pre>

<ul>
<li>当 <code>Python</code> 解释器 <strong>抛出异常</strong> 时，<strong>最后一行错误信息的第一个单词，就是错误类型</strong></li>
</ul>

<h4 id="toc_7">异常类型捕获演练 —— 要求用户输入整数</h4>

<p><strong>需求</strong></p>

<ol>
<li>提示用户输入一个整数</li>
<li>使用 <code>8</code> 除以用户输入的整数并且输出</li>
</ol>

<pre><code class="language-python">try:
    num = int(input(&quot;请输入整数：&quot;))
    result = 8 / num
    print(result)
except ValueError:
    print(&quot;请输入正确的整数&quot;)
except ZeroDivisionError:
    print(&quot;除 0 错误&quot;)

</code></pre>

<h4 id="toc_8">捕获未知错误</h4>

<ul>
<li>在开发时，<strong>要预判到所有可能出现的错误</strong>，还是有一定难度的</li>
<li>如果希望程序 <strong>无论出现任何错误</strong>，都不会因为 <code>Python</code> 解释器 <strong>抛出异常而被终止</strong>，可以再增加一个 <code>except</code></li>
</ul>

<p>语法如下：</p>

<pre><code class="language-python">except Exception as result:
    print(&quot;未知错误 %s&quot; % result)
</code></pre>

<h3 id="toc_9">2.3 异常捕获完整语法</h3>

<ul>
<li>在实际开发中，为了能够处理复杂的异常情况，完整的异常语法如下：</li>
</ul>

<blockquote>
<p>提示：</p>

<ul>
<li>有关完整语法的应用场景，在后续学习中，<strong>结合实际的案例</strong>会更好理解</li>
<li>现在先对这个语法结构有个印象即可</li>
</ul>
</blockquote>

<pre><code class="language-python">try:
    # 尝试执行的代码
    pass
except 错误类型1:
    # 针对错误类型1，对应的代码处理
    pass
except 错误类型2:
    # 针对错误类型2，对应的代码处理
    pass
except (错误类型3, 错误类型4):
    # 针对错误类型3 和 4，对应的代码处理
    pass
except Exception as result:
    # 打印错误信息
    print(result)
else:
    # 没有异常才会执行的代码
    pass
finally:
    # 无论是否有异常，都会执行的代码
    print(&quot;无论是否有异常，都会执行的代码&quot;)
</code></pre>

<ul>
<li><code>else</code> 只有在没有异常时才会执行的代码</li>
<li><p><code>finally</code> 无论是否有异常，都会执行的代码</p></li>
<li><p>之前一个演练的 <strong>完整捕获异常</strong> 的代码如下：</p></li>
</ul>

<pre><code class="language-python">try:
    num = int(input(&quot;请输入整数：&quot;))
    result = 8 / num
    print(result)
except ValueError:
    print(&quot;请输入正确的整数&quot;)
except ZeroDivisionError:
    print(&quot;除 0 错误&quot;)
except Exception as result:
    print(&quot;未知错误 %s&quot; % result)
else:
    print(&quot;正常执行&quot;)
finally:
    print(&quot;执行完成，但是不保证正确&quot;)

</code></pre>

<h2 id="toc_10">03. 异常的传递</h2>

<ul>
<li><strong>异常的传递</strong> —— 当 <strong>函数/方法</strong> 执行 <strong>出现异常</strong>，会 <strong>将异常传递</strong> 给 函数/方法 的 <strong>调用一方</strong></li>
<li>如果 <strong>传递到主程序</strong>，仍然 <strong>没有异常处理</strong>，程序才会被终止</li>
</ul>

<blockquote>
<p>提示</p>
</blockquote>

<ul>
<li>在开发中，可以在主函数中增加 <strong>异常捕获</strong></li>
<li>而在主函数中调用的其他函数，只要出现异常，都会传递到主函数的 <strong>异常捕获</strong> 中</li>
<li>这样就不需要在代码中，增加大量的 <strong>异常捕获</strong>，能够保证代码的整洁</li>
</ul>

<p><strong>需求</strong></p>

<ol>
<li>定义函数 <code>demo1()</code> <strong>提示用户输入一个整数并且返回</strong></li>
<li>定义函数 <code>demo2()</code> 调用 <code>demo1()</code></li>
<li>在主程序中调用 <code>demo2()</code></li>
</ol>

<pre><code class="language-python">def demo1():
    return int(input(&quot;请输入一个整数：&quot;))


def demo2():
    return demo1()

try:
    print(demo2())
except ValueError:
    print(&quot;请输入正确的整数&quot;)
except Exception as result:
    print(&quot;未知错误 %s&quot; % result)

</code></pre>

<h2 id="toc_11">04. 抛出 <code>raise</code> 异常</h2>

<h3 id="toc_12">4.1 应用场景</h3>

<ul>
<li>在开发中，除了 <strong>代码执行出错</strong> <code>Python</code> 解释器会 <strong>抛出</strong> 异常之外</li>
<li>还可以根据 <strong>应用程序</strong> <strong>特有的业务需求</strong> <strong>主动抛出异常</strong></li>
</ul>

<p><strong>示例</strong></p>

<ul>
<li>提示用户 <strong>输入密码</strong>，如果 <strong>长度少于 8</strong>，抛出 <strong>异常</strong></li>
</ul>

<p><img src="media/15016413521006/024_%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8.png" alt="024_自定义异常" style="width:822px;"/>￼</p>

<p><strong>注意</strong></p>

<ul>
<li>当前函数 <strong>只负责</strong> 提示用户输入密码，如果 <strong>密码长度不正确，需要其他的函数进行额外处理</strong></li>
<li>因此可以 <strong>抛出异常</strong>，由其他需要处理的函数 <strong>捕获异常</strong></li>
</ul>

<h3 id="toc_13">4.2 抛出异常</h3>

<ul>
<li><code>Python</code> 中提供了一个 <code>Exception</code> <strong>异常类</strong></li>
<li>在开发时，如果满足 <strong>特定业务需求时</strong>，希望 <strong>抛出异常</strong>，可以：

<ol>
<li><strong>创建</strong> 一个 <code>Exception</code> 的 <strong>对象</strong></li>
<li>使用 <code>raise</code> <strong>关键字</strong> 抛出 <strong>异常对象</strong></li>
</ol></li>
</ul>

<p><strong>需求</strong></p>

<ul>
<li>定义 <code>input_password</code> 函数，提示用户输入密码</li>
<li>如果用户输入长度 &lt; 8，抛出异常</li>
<li>如果用户输入长度 &gt;=8，返回输入的密码</li>
</ul>

<pre><code class="language-python">def input_password():

    # 1. 提示用户输入密码
    pwd = input(&quot;请输入密码：&quot;)

    # 2. 判断密码长度，如果长度 &gt;= 8，返回用户输入的密码
    if len(pwd) &gt;= 8:
        return pwd

    # 3. 密码长度不够，需要抛出异常
    # 1&gt; 创建异常对象 - 使用异常的错误信息字符串作为参数
    ex = Exception(&quot;密码长度不够&quot;)

    # 2&gt; 抛出异常对象
    raise ex


try:
    user_pwd = input_password()
    print(user_pwd)
except Exception as result:
    print(&quot;发现错误：%s&quot; % result)

</code></pre>

</div></body>

</html>
